pub mod longest_common_prefix;
pub mod reverse_string;
mod array_pair_sum;
mod two_sum_ii;
mod remove_element;
mod max_consecutive_ones;
mod minimum_size_subarray_sum;
mod bus_routes;
mod sort_vowels_in_a_string;
mod unique_length_3_palindromic;
mod maximum_element_after_decrementing_and_rearranging;
mod find_unique_binary_string;
mod minimize_maximum_pair_sum_in_array;